version: 2.1
jobs:
  setup:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run: 
          name: install ansible
          command: |
            apk add --update ansible
      - run:
          name: run ansible
          command: |
            ansible-playbook -i inventory.txt main.yml
workflows:
  default:
    jobs:
      - setup