version: 2.1
jobs:
  smoke-test:
    docker:
      - image: alpine:latest 
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add --update python3
            apk add --update curl
      - run:
          name: Backend smoke test.
          command: |
            if curl "http://18.212.68.192:3030/api/status" | grep "ok"
            then
                return 0
            else
                return 1
            fi
      - run:
          name: Frontend smoke test.
          command: |
            URL="http://udapeople-6bba1cc.s3-website-us-east-1.amazonaws.com/#/employees"            
            echo ${URL} 
            if curl -s ${URL} | grep "Welcome"
            then
                return 0
            else
                return 1
            fi
workflows:
  default:
    jobs:
      - smoke-test