version: 2.1
commands:
  destroy-environment:
    description: Destroy backend and frontend cloudformation stacks given a workflow ID.
    parameters:
      workflow_id:
        type: string      
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            echo "Destroying environment: << parameters.workflow_id >> "
            aws s3 rm s3://udapeople-<< parameters.workflow_id >> --recursive
            aws cloudformation delete-stack --stack-name udapeople-backend-<< parameters.workflow_id >>
            aws cloudformation delete-stack --stack-name udapeople-frontend-<< parameters.workflow_id >>

  revert-migrations:
    description: Revert the last migration
    parameters:
      workflow_id:
          type: string      
    steps:
      - run:
          name: Revert migrations
          when: on_fail
          command: |
            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
            then
                cd ~/project/backend
                touch .env
                echo "NODE_ENV=local" >> .env
                echo "VERSION=1" >> .env
                echo "TYPEORM_CONNECTION=$TYPEORM_CONNECTION" >> .env
                echo "TYPEORM_MIGRATIONS_DIR=$TYPEORM_MIGRATIONS_DIR" >> .env
                echo "TYPEORM_ENTITIES=$TYPEORM_ENTITIES" >> .env
                echo "TYPEORM_MIGRATIONS=$TYPEORM_MIGRATIONS" >> .env
                echo "TYPEORM_HOST=$TYPEORM_HOST" >> .env
                echo "TYPEORM_PORT=5432" >> .env >> .env
                echo "TYPEORM_USERNAME=$TYPEORM_USERNAME" >> .env
                echo "TYPEORM_PASSWORD=$TYPEORM_PASSWORD" >> .env
                echo "TYPEORM_DATABASE=$TYPEORM_DATABASE" >> .env
                npm install
                npm run migrations:revert
            fi
jobs:

  cleanup:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Remove old stacks and files
          command: |
            export OldWorkflowID=$(aws cloudformation \
                    list-exports --query "Exports[?Name==\`ID\`].Value" \
                    --no-paginate --output text)
            echo OldWorkflowID: "${OldWorkflowID}"
            echo CIRCLE_WORKFLOW_ID "${CIRCLE_WORKFLOW_ID:0:7}"
            export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
                    --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
            echo Stack names: "${STACKS[@]}"
            if [[ "${CIRCLE_WORKFLOW_ID:0:7}" != "${OldWorkflowID}" ]]
            then
                echo "-------------------Delete confirmed----------------------"
                aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
                aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
                aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
            else
                echo "-------------------Cannot Cleanup----------------------"
            fi
  
workflows:
  default:
    jobs:
      - cleanup