version: 2.1
commands:
  destroy-environment:
    description: Destroy backend and frontend cloudformation stacks given a workflow ID.
    parameters:
      workflow_id:
        type: string      
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            echo "Destroying environment: << parameters.workflow_id >> "
            aws s3 rm s3://udapeople-<< parameters.workflow_id >> --recursive
            aws cloudformation delete-stack --stack-name udapeople-backend-<< parameters.workflow_id >>
            aws cloudformation delete-stack --stack-name udapeople-frontend-<< parameters.workflow_id >>

  revert-migrations:
    description: Revert the last migration
    parameters:
      workflow_id:
          type: string      
    steps:
      - run:
          name: Revert migrations
          when: on_fail
          command: |
            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
            then
                cd ~/project/backend
                npm install
                npm run migrations:revert
            fi
jobs:

  run-migrations:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run: 
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install awscli
      - run:
          name: Run migrations
          command: |
            cd backend
            npm install
            npm run migrations > migrations_dump.txt
      - run:
          name: Send migration results to memstash
          command: |
            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
            then
                curl https://kvdb.io/8tMADQzHuts6vnHp3XzRuK/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '1'
            fi

  smoke-test:
    docker:
      - image: python:3.7-alpine3.11 
    steps:
      - checkout
      - run:
          name: test
          command: | 
            echo "has been executed successfully." > ~/project/backend/migrations_dump.txt
      - run:
          name: Install dependencies
          command: |
            apk add --update npm
            apk add --update nodejs
            apk add --update curl
            pip install awscli
      - run:
          name: Backend smoke test.
          command: |
            return 0
      - run:
          name: Frontend smoke test.
          command: |
            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
            echo ${URL} 
            if curl -s ${URL} | grep "Welcome"
            then
                return 1
            else
                return 1
            fi
      - destroy-environment:
          workflow_id: '3c8c2c9'
      - revert-migrations:
          workflow_id: '3c8c2c9'
  
workflows:
  default:
    jobs:
      - run-migrations
      - smoke-test:
          requires: [run-migrations]