version: 2.1
jobs:
  setup:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["d4:32:2f:c0:9d:e6:ba:29:12:f8:99:38:cf:27:75:75"]
      - run: 
          name: install ansible
          command: |
            apk add --update ansible
      - run:
          name: run ansible
          command: |
            ansible-playbook -i inventory.txt main.yml
workflows:
  default:
    jobs:
      - setup