- name: Set
  become: true
  shell: |
    cd /home/ec2-user/udacity_project3/backend
    touch .env
    echo "NODE_ENV=local" >> .env
    echo "VERSION=1" >> .env
    echo "TYPEORM_CONNECTION="{{ lookup('env', 'TYPEORM_CONNECTION')}}"" >> .env
    echo "TYPEORM_MIGRATIONS_DIR="{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}"" >> .env
    echo "TYPEORM_ENTITIES="{{ lookup('env', 'TYPEORM_ENTITIES')}}"" >> .env
    echo "TYPEORM_MIGRATIONS="{{ lookup('env', 'TYPEORM_MIGRATIONS')}}"" >> .env
    echo "TYPEORM_HOST="{{ lookup('env', 'TYPEORM_HOST')}}"" >> .env
    echo "TYPEORM_PORT=5432" >> .env >> .env
    echo "TYPEORM_USERNAME="{{ lookup('env', 'TYPEORM_USERNAME')}}"" >> .env
    echo "TYPEORM_PASSWORD="{{ lookup('env', 'TYPEORM_PASSWORD')}}"" >> .env
    echo "TYPEORM_DATABASE="{{ lookup('env', 'TYPEORM_DATABASE')}}"" >> .env

- name: start app
  shell: |
    pm2 start npm -- start